language: php

php:
  - 5.2
  - 5.3
  - 5.4
  
before_script:
  - mysql -e 'CREATE DATABASE cakephp_test;'
  - chmod -R 777 ./app/tmp
  - chmod +x ./app/Console/cake
  - cp ./app/Config/config.php.default ./app/Config/config.php
  - pear channel-discover pear.cakephp.org
  - pear install --alldeps cakephp/CakePHP_CodeSniffer
  - phpenv rehash
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'persistent' => false,
      'datasource' => 'Database/Mysql',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'database' => 'cakephp_test',
      'prefix' => 'test',
    );
    public \$test = array(
      'persistent' => false,
      'datasource' => 'Database/Mysql',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'database' => 'cakephp_test',
      'prefix' => 'test_',
    );    }" > app/Config/database.php
  - echo -e "n\ny\n" | ./app/Console/cake schema create --name laser

script:
  - ./app/Console/cake test app AllTests 
  
notifications:
  email: false