language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  include:
    - php: 5.4
      env:
        - PHPCS=1
before_script:
  - mysql -e 'CREATE DATABASE cakephp_test;'
  - chmod -R 777 ./app/tmp
  - chmod +x ./app/Console/cake
  - cp ./app/Config/config.php.default ./app/Config/config.php
  - sh -c "if [ -z "$PHPCS" ] && [ $(phpenv version-name) = "5.4" ]; then composer install --dev --no-interaction; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then pear channel-discover pear.cakephp.org; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then pear install --alldeps cakephp/CakePHP_CodeSniffer; fi"
  - phpenv rehash
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {

    public \$default = array(
      'persistent' => false,
      'datasource' => 'Database/Mysql',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'database' => 'cakephp_test',
      'prefix' => 'test',
    );

    public \$test = array(
      'persistent' => false,
      'datasource' => 'Database/Mysql',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'database' => 'cakephp_test',
      'prefix' => 'test_',
    );
        }" > app/Config/database.php
  - echo -e "n\ny\n" | ./app/Console/cake schema create --name laser
  - sh -c "if [ '$PHPCS' = '1' ]; then rm app/Config/database.php; cp app/Config/database.php.default app/Config/database.php; fi"

script:
  - sh -c "if [ '$PHPCS' = '1' ]; then phpcs -p -n --ignore=\*.css,\*.js,\*Plugin\*,\*vendor\* --extensions=php --standard=CakePHP ./app/; elif [ $(phpenv version-name) = "5.4" ]; then ./app/Console/cake test app AllTests --coverage-clover=./clover.xml; else ./app/Console/cake test app AllTests; fi"

after_script:
  - sh -c "if [ -z "$PHPCS" ] && [ $(phpenv version-name) = "5.4" ]; then php vendor/bin/coveralls; fi"

notifications:
  email: false